
package com.ibm.selmate.util;

public enum CommandTypes {
	ACCEPT_ALERT, ACTIVATE, ASSERT, ASSIGN, AUTHENTICATE, CLICK, DELAY, DISMISS_ALERT, DRAG_FROM, DROP_TO, WAIT, OPEN,
	READVALUE, READSTATE, REFRESH, SELECT_OPTION, DESELECT_OPTION, SWITCH_FRAME, SWITCH_PARENT_WINDOW, SWITCH_WINDOW,
	SWITCH_TO_DEFAULT_CONTENT, WRITE, WRITE_PASSWORD, SELECT, DESELECT, HIST_BKWD, HIST_FWD, SWITCH_ALERT, SCREENSHOT,
	PRINT, CLOSE
}
