package com.ibm.selmate.util;

public interface ExceptionTypes {

	String ELEMENT_NOT_VISIBLE_ERROR = "ELEMENT_NOT_VISIBLE_ERROR";

	String IME_ACTIVATION_FAILED_ERROR = "IME_ACTIVATION_FAILED_ERROR";

	String IME_NOT_SUPPORTED_ERROR = "IME_NOT_SUPPORTED_ERROR";

	String INVALID_ELEMENT_STATE_ERROR = "INVALID_ELEMENT_STATE_ERROR";

	String INVALID_COOKIE_DOMAIN_ERROR = "INVALID_COOKIE_DOMAIN_ERROR";

	String INVALID_TARGET_ERROR = "INVALID_TARGET_ERROR";

	String INVALID_SELECTOR_ERROR = "INVALID_SELECTOR_ERROR";

	String NO_ALERT_PRESENT_ERROR = "NO_ALERT_PRESENT_ERROR";

	String NO_SUCH_ELEMENT_ERROR = "NO_SUCH_ELEMENT_ERROR";

	String NO_SUCH_FRAME_ERROR = "NO_SUCH_FRAME_ERROR";

	String NO_SUCH_WINDOW_ERROR = "NO_SUCH_WINDOW_ERROR";

	String STALE_ELEMENT_REFERENCE_ERROR = "STALE_ELEMENT_REFERENCE_ERROR";

	String TIMEOUT_ERROR = "TIMEOUT_ERROR";

	String UNABLE_TO_SET_COOKIE_ERROR = "UNABLE_TO_SET_COOKIE_ERROR";

	String UNEXPECTED_TAG_NAME_ERROR = "UNEXPECTED_TAG_NAME_ERROR";

	String WEBDRIVER_ERROR = "WEBDRIVER_ERROR";

	String UNKNOWN_ERROR = "UNKNOWN_ERROR";
}
