//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * This Complex Type represents an abstraction of all Commands to be used for
 * communication with the browser.
 * 
 * 
 * <p>
 * Java class for AbstractCommandType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
&lt;complexType name="AbstractCommandType">
  &lt;complexContent>
    &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      &lt;sequence>
        &lt;element name="stepDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
      &lt;/sequence>
    &lt;/restriction>
  &lt;/complexContent>
&lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractCommandType", propOrder = { "stepDescription" })
@XmlSeeAlso({ RefreshCommandType.class, PrintCommandType.class, OpenURLCommandType.class, AssignCommandType.class,
		SwitchToParentWindowCommandType.class, CustomCommandType.class, ScreenshotCommandType.class,
		AbstractAlertCommandType.class, NavigationHistoryCommandType.class, AssertCommandType.class,
		SwitchToDefaultContentCommandType.class, SwitchToFrameCommandType.class, SwitchToWindowCommandType.class,
		CloseCommandType.class, WaitCommandType.class, AbstractElementInteractionCommandType.class })
public abstract class AbstractCommandType {

	protected String stepDescription;

	/**
	 * Gets the value of the stepDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStepDescription() {
		return stepDescription;
	}

	/**
	 * Sets the value of the stepDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStepDescription(String value) {
		this.stepDescription = value;
	}

}
