//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AbstractReadCommandType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
&lt;complexType name="AbstractReadCommandType">
  &lt;complexContent>
    &lt;extension base="{http://www.ibm.com/selmate}AbstractElementInteractionCommandType">
      &lt;sequence>
        &lt;element name="variable" type="{http://www.w3.org/2001/XMLSchema}string"/>
      &lt;/sequence>
    &lt;/extension>
  &lt;/complexContent>
&lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractReadCommandType", propOrder = { "variable" })
@XmlSeeAlso({ ReadStateCommandType.class, ReadValueCommandType.class })
public abstract class AbstractReadCommandType extends AbstractElementInteractionCommandType {

	@XmlElement(required = true)
	protected String variable;

	/**
	 * Gets the value of the variable property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVariable() {
		return variable;
	}

	/**
	 * Sets the value of the variable property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setVariable(String value) {
		this.variable = value;
	}

}
