//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * This Complex Type represents an abstraction of all Select Commands(e.g.
 * Selection of radio button, checkbox, listbox, dropdown etc.) to be used for
 * communication with the browser.
 * 
 * 
 * <p>
 * Java class for AbstractSelectCommandType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
&lt;complexType name="AbstractSelectCommandType">
  &lt;complexContent>
    &lt;extension base="{http://www.ibm.com/selmate}AbstractElementInteractionCommandType">
      &lt;attribute name="status" use="required" type="{http://www.ibm.com/selmate}SelectionStatusType" />
    &lt;/extension>
  &lt;/complexContent>
&lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractSelectCommandType")
@XmlSeeAlso({ SelectOptionsCommandType.class, SelectCommandType.class })
public abstract class AbstractSelectCommandType extends AbstractElementInteractionCommandType {

	@XmlAttribute(name = "status", required = true)
	protected SelectionStatusType status;

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link SelectionStatusType }
	 * 
	 */
	public SelectionStatusType getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value allowed object is {@link SelectionStatusType }
	 * 
	 */
	public void setStatus(SelectionStatusType value) {
		this.status = value;
	}

}
