//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AssertCommandType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
&lt;complexType name="AssertCommandType">
  &lt;complexContent>
    &lt;extension base="{http://www.ibm.com/selmate}AbstractCommandType">
      &lt;sequence>
        &lt;element name="actualValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
        &lt;element name="expectedValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
        &lt;element name="failureMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
      &lt;/sequence>
      &lt;attribute name="type" type="{http://www.ibm.com/selmate}AssertType" />
      &lt;attribute name="comparisonType" type="{http://www.ibm.com/selmate}ComparisonType" />
    &lt;/extension>
  &lt;/complexContent>
&lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssertCommandType", propOrder = { "actualValue", "expectedValue", "failureMsg" })
public class AssertCommandType extends AbstractCommandType {

	@XmlElement(required = true)
	protected String actualValue;
	@XmlElement(required = true)
	protected String expectedValue;
	protected String failureMsg;
	@XmlAttribute(name = "type")
	protected AssertType type;
	@XmlAttribute(name = "comparisonType")
	protected ComparisonType comparisonType;

	/**
	 * Gets the value of the actualValue property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getActualValue() {
		return actualValue;
	}

	/**
	 * Sets the value of the actualValue property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setActualValue(String value) {
		this.actualValue = value;
	}

	/**
	 * Gets the value of the expectedValue property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExpectedValue() {
		return expectedValue;
	}

	/**
	 * Sets the value of the expectedValue property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setExpectedValue(String value) {
		this.expectedValue = value;
	}

	/**
	 * Gets the value of the failureMsg property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFailureMsg() {
		return failureMsg;
	}

	/**
	 * Sets the value of the failureMsg property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setFailureMsg(String value) {
		this.failureMsg = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link AssertType }
	 * 
	 */
	public AssertType getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value allowed object is {@link AssertType }
	 * 
	 */
	public void setType(AssertType value) {
		this.type = value;
	}

	/**
	 * Gets the value of the comparisonType property.
	 * 
	 * @return possible object is {@link ComparisonType }
	 * 
	 */
	public ComparisonType getComparisonType() {
		return comparisonType;
	}

	/**
	 * Sets the value of the comparisonType property.
	 * 
	 * @param value allowed object is {@link ComparisonType }
	 * 
	 */
	public void setComparisonType(ComparisonType value) {
		this.comparisonType = value;
	}

}
