//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CustomCommandType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
&lt;complexType name="CustomCommandType">
  &lt;complexContent>
    &lt;extension base="{http://www.ibm.com/selmate}AbstractCommandType">
      &lt;sequence>
        &lt;element name="commandClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
        &lt;element name="arguments">
          &lt;complexType>
            &lt;complexContent>
              &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                &lt;sequence>
                  &lt;element name="argument" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
                &lt;/sequence>
              &lt;/restriction>
            &lt;/complexContent>
          &lt;/complexType>
        &lt;/element>
      &lt;/sequence>
    &lt;/extension>
  &lt;/complexContent>
&lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomCommandType", propOrder = { "commandClass", "arguments" })
public class CustomCommandType extends AbstractCommandType {

	@XmlElement(required = true)
	protected String commandClass;
	@XmlElement(required = true)
	protected CustomCommandType.Arguments arguments;

	/**
	 * Gets the value of the commandClass property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCommandClass() {
		return commandClass;
	}

	/**
	 * Sets the value of the commandClass property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCommandClass(String value) {
		this.commandClass = value;
	}

	/**
	 * Gets the value of the arguments property.
	 * 
	 * @return possible object is {@link CustomCommandType.Arguments }
	 * 
	 */
	public CustomCommandType.Arguments getArguments() {
		return arguments;
	}

	/**
	 * Sets the value of the arguments property.
	 * 
	 * @param value allowed object is {@link CustomCommandType.Arguments }
	 * 
	 */
	public void setArguments(CustomCommandType.Arguments value) {
		this.arguments = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 &lt;complexType>
	   &lt;complexContent>
	     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	       &lt;sequence>
	         &lt;element name="argument" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
	       &lt;/sequence>
	     &lt;/restriction>
	   &lt;/complexContent>
	 &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "argument" })
	public static class Arguments {

		protected List<Object> argument;

		/**
		 * Gets the value of the argument property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the argument property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getArgument().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Object }
		 * 
		 * 
		 */
		public List<Object> getArgument() {
			if (argument == null) {
				argument = new ArrayList<Object>();
			}
			return this.argument;
		}

	}

}
