//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ElementLocatorType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
&lt;complexType name="ElementLocatorType">
  &lt;complexContent>
    &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      &lt;choice>
        &lt;element name="id" type="{http://www.ibm.com/selmate}ElementIdType"/>
        &lt;element name="xpath" type="{http://www.ibm.com/selmate}ElementNameType"/>
        &lt;element name="className" type="{http://www.ibm.com/selmate}ElementClassNameType"/>
        &lt;element name="tagName" type="{http://www.ibm.com/selmate}ElementTagNameType"/>
        &lt;element name="cssSelector" type="{http://www.ibm.com/selmate}ElementCSSSelectorType"/>
        &lt;element name="linkText" type="{http://www.ibm.com/selmate}LinkElementTextType"/>
        &lt;element name="partialLinkText" type="{http://www.ibm.com/selmate}LinkElementPartialTextType"/>
      &lt;/choice>
    &lt;/restriction>
  &lt;/complexContent>
&lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementLocatorType", propOrder = { "id", "xpath", "className", "tagName", "cssSelector", "linkText",
		"partialLinkText" })
public class ElementLocatorType {

	protected String id;
	protected String xpath;
	protected String className;
	protected String tagName;
	protected String cssSelector;
	protected String linkText;
	protected String partialLinkText;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the xpath property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXpath() {
		return xpath;
	}

	/**
	 * Sets the value of the xpath property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setXpath(String value) {
		this.xpath = value;
	}

	/**
	 * Gets the value of the className property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClassName() {
		return className;
	}

	/**
	 * Sets the value of the className property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setClassName(String value) {
		this.className = value;
	}

	/**
	 * Gets the value of the tagName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTagName() {
		return tagName;
	}

	/**
	 * Sets the value of the tagName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTagName(String value) {
		this.tagName = value;
	}

	/**
	 * Gets the value of the cssSelector property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCssSelector() {
		return cssSelector;
	}

	/**
	 * Sets the value of the cssSelector property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCssSelector(String value) {
		this.cssSelector = value;
	}

	/**
	 * Gets the value of the linkText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLinkText() {
		return linkText;
	}

	/**
	 * Sets the value of the linkText property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setLinkText(String value) {
		this.linkText = value;
	}

	/**
	 * Gets the value of the partialLinkText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPartialLinkText() {
		return partialLinkText;
	}

	/**
	 * Sets the value of the partialLinkText property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPartialLinkText(String value) {
		this.partialLinkText = value;
	}

}
