//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ElementType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
&lt;complexType name="ElementType">
  &lt;complexContent>
    &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      &lt;sequence>
        &lt;element name="locator" type="{http://www.ibm.com/selmate}ElementLocatorType"/>
      &lt;/sequence>
    &lt;/restriction>
  &lt;/complexContent>
&lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementType", propOrder = { "locator" })
public class ElementType {

	@XmlElement(required = true)
	protected ElementLocatorType locator;

	/**
	 * Gets the value of the locator property.
	 * 
	 * @return possible object is {@link ElementLocatorType }
	 * 
	 */
	public ElementLocatorType getLocator() {
		return locator;
	}

	/**
	 * Sets the value of the locator property.
	 * 
	 * @param value allowed object is {@link ElementLocatorType }
	 * 
	 */
	public void setLocator(ElementLocatorType value) {
		this.locator = value;
	}

}
