//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for NavigationHistoryCommandType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
&lt;complexType name="NavigationHistoryCommandType">
  &lt;complexContent>
    &lt;extension base="{http://www.ibm.com/selmate}AbstractCommandType">
      &lt;attribute name="type" type="{http://www.ibm.com/selmate}NavigationType" />
    &lt;/extension>
  &lt;/complexContent>
&lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NavigationHistoryCommandType")
public class NavigationHistoryCommandType extends AbstractCommandType {

	@XmlAttribute(name = "type")
	protected NavigationType type;

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link NavigationType }
	 * 
	 */
	public NavigationType getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value allowed object is {@link NavigationType }
	 * 
	 */
	public void setType(NavigationType value) {
		this.type = value;
	}

}
