//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.ibm.selmate.jaxb.stubs package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema
	 * derived classes for package: com.ibm.selmate.jaxb.stubs
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link WaitCommandType }
	 * 
	 */
	public WaitCommandType createWaitCommandType() {
		return new WaitCommandType();
	}

	/**
	 * Create an instance of {@link SelectOptionsCommandType }
	 * 
	 */
	public SelectOptionsCommandType createSelectOptionsCommandType() {
		return new SelectOptionsCommandType();
	}

	/**
	 * Create an instance of {@link SelectOptionsCommandType.Options }
	 * 
	 */
	public SelectOptionsCommandType.Options createSelectOptionsCommandTypeOptions() {
		return new SelectOptionsCommandType.Options();
	}

	/**
	 * Create an instance of {@link CustomCommandType }
	 * 
	 */
	public CustomCommandType createCustomCommandType() {
		return new CustomCommandType();
	}

	/**
	 * Create an instance of {@link Script }
	 * 
	 */
	public Script createScript() {
		return new Script();
	}

	/**
	 * Create an instance of {@link RefreshCommandType }
	 * 
	 */
	public RefreshCommandType createRefreshCommandType() {
		return new RefreshCommandType();
	}

	/**
	 * Create an instance of {@link ElementLocatorType }
	 * 
	 */
	public ElementLocatorType createElementLocatorType() {
		return new ElementLocatorType();
	}

	/**
	 * Create an instance of {@link PrintCommandType }
	 * 
	 */
	public PrintCommandType createPrintCommandType() {
		return new PrintCommandType();
	}

	/**
	 * Create an instance of {@link AcceptAlertCommandType }
	 * 
	 */
	public AcceptAlertCommandType createAcceptAlertCommandType() {
		return new AcceptAlertCommandType();
	}

	/**
	 * Create an instance of {@link WriteTextCommandType }
	 * 
	 */
	public WriteTextCommandType createWriteTextCommandType() {
		return new WriteTextCommandType();
	}

	/**
	 * Create an instance of {@link DismissAlertCommandType }
	 * 
	 */
	public DismissAlertCommandType createDismissAlertCommandType() {
		return new DismissAlertCommandType();
	}

	/**
	 * Create an instance of {@link OpenURLCommandType }
	 * 
	 */
	public OpenURLCommandType createOpenURLCommandType() {
		return new OpenURLCommandType();
	}

	/**
	 * Create an instance of {@link AssignCommandType }
	 * 
	 */
	public AssignCommandType createAssignCommandType() {
		return new AssignCommandType();
	}

	/**
	 * Create an instance of {@link ReadStateCommandType }
	 * 
	 */
	public ReadStateCommandType createReadStateCommandType() {
		return new ReadStateCommandType();
	}

	/**
	 * Create an instance of {@link SwitchToParentWindowCommandType }
	 * 
	 */
	public SwitchToParentWindowCommandType createSwitchToParentWindowCommandType() {
		return new SwitchToParentWindowCommandType();
	}

	/**
	 * Create an instance of {@link ElementType }
	 * 
	 */
	public ElementType createElementType() {
		return new ElementType();
	}

	/**
	 * Create an instance of {@link ScreenshotCommandType }
	 * 
	 */
	public ScreenshotCommandType createScreenshotCommandType() {
		return new ScreenshotCommandType();
	}

	/**
	 * Create an instance of {@link AuthenticateAlertCommandType }
	 * 
	 */
	public AuthenticateAlertCommandType createAuthenticateAlertCommandType() {
		return new AuthenticateAlertCommandType();
	}

	/**
	 * Create an instance of {@link NavigationHistoryCommandType }
	 * 
	 */
	public NavigationHistoryCommandType createNavigationHistoryCommandType() {
		return new NavigationHistoryCommandType();
	}

	/**
	 * Create an instance of {@link AssertCommandType }
	 * 
	 */
	public AssertCommandType createAssertCommandType() {
		return new AssertCommandType();
	}

	/**
	 * Create an instance of {@link SelectCommandType }
	 * 
	 */
	public SelectCommandType createSelectCommandType() {
		return new SelectCommandType();
	}

	/**
	 * Create an instance of {@link DragCommandType }
	 * 
	 */
	public DragCommandType createDragCommandType() {
		return new DragCommandType();
	}

	/**
	 * Create an instance of {@link SwitchToDefaultContentCommandType }
	 * 
	 */
	public SwitchToDefaultContentCommandType createSwitchToDefaultContentCommandType() {
		return new SwitchToDefaultContentCommandType();
	}

	/**
	 * Create an instance of {@link SwitchToFrameCommandType }
	 * 
	 */
	public SwitchToFrameCommandType createSwitchToFrameCommandType() {
		return new SwitchToFrameCommandType();
	}

	/**
	 * Create an instance of {@link ReadValueCommandType }
	 * 
	 */
	public ReadValueCommandType createReadValueCommandType() {
		return new ReadValueCommandType();
	}

	/**
	 * Create an instance of {@link SwitchToWindowCommandType }
	 * 
	 */
	public SwitchToWindowCommandType createSwitchToWindowCommandType() {
		return new SwitchToWindowCommandType();
	}

	/**
	 * Create an instance of {@link CloseCommandType }
	 * 
	 */
	public CloseCommandType createCloseCommandType() {
		return new CloseCommandType();
	}

	/**
	 * Create an instance of {@link ClickCommandType }
	 * 
	 */
	public ClickCommandType createClickCommandType() {
		return new ClickCommandType();
	}

	/**
	 * Create an instance of {@link DropCommandType }
	 * 
	 */
	public DropCommandType createDropCommandType() {
		return new DropCommandType();
	}

	/**
	 * Create an instance of {@link WritePasswordCommandType }
	 * 
	 */
	public WritePasswordCommandType createWritePasswordCommandType() {
		return new WritePasswordCommandType();
	}

	/**
	 * Create an instance of {@link ActivateCommandType }
	 * 
	 */
	public ActivateCommandType createActivateCommandType() {
		return new ActivateCommandType();
	}

	/**
	 * Create an instance of {@link WaitCommandType.Duration }
	 * 
	 */
	public WaitCommandType.Duration createWaitCommandTypeDuration() {
		return new WaitCommandType.Duration();
	}

	/**
	 * Create an instance of {@link SelectOptionsCommandType.Options.All }
	 * 
	 */
	public SelectOptionsCommandType.Options.All createSelectOptionsCommandTypeOptionsAll() {
		return new SelectOptionsCommandType.Options.All();
	}

	/**
	 * Create an instance of {@link SelectOptionsCommandType.Options.Option }
	 * 
	 */
	public SelectOptionsCommandType.Options.Option createSelectOptionsCommandTypeOptionsOption() {
		return new SelectOptionsCommandType.Options.Option();
	}

	/**
	 * Create an instance of {@link CustomCommandType.Arguments }
	 * 
	 */
	public CustomCommandType.Arguments createCustomCommandTypeArguments() {
		return new CustomCommandType.Arguments();
	}

}
