//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * This Complex Type represents a command to fetch attribute value of an HTML
 * element from the browser.
 * 
 * 
 * <p>
 * Java class for ReadValueCommandType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
&lt;complexType name="ReadValueCommandType">
  &lt;complexContent>
    &lt;extension base="{http://www.ibm.com/selmate}AbstractReadCommandType">
      &lt;attribute name="attributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
    &lt;/extension>
  &lt;/complexContent>
&lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReadValueCommandType")
public class ReadValueCommandType extends AbstractReadCommandType {

	@XmlAttribute(name = "attributeName")
	protected String attributeName;

	/**
	 * Gets the value of the attributeName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeName() {
		return attributeName;
	}

	/**
	 * Sets the value of the attributeName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeName(String value) {
		this.attributeName = value;
	}

}
