//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * This Complex Type represents Select Command(e.g. Selection of options in
 * listbox, dropdown etc.) to be used for communication with the browser.
 * 
 * 
 * <p>
 * Java class for SelectOptionsCommandType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
&lt;complexType name="SelectOptionsCommandType">
  &lt;complexContent>
    &lt;extension base="{http://www.ibm.com/selmate}AbstractSelectCommandType">
      &lt;sequence>
        &lt;element name="options">
          &lt;complexType>
            &lt;complexContent>
              &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                &lt;sequence>
                  &lt;choice>
                    &lt;element name="all">
                      &lt;complexType>
                        &lt;complexContent>
                          &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                            &lt;sequence>
                            &lt;/sequence>
                          &lt;/restriction>
                        &lt;/complexContent>
                      &lt;/complexType>
                    &lt;/element>
                    &lt;element name="option" maxOccurs="unbounded">
                      &lt;complexType>
                        &lt;complexContent>
                          &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                            &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                            &lt;attribute name="by" use="required" type="{http://www.ibm.com/selmate}OptionSelectionType" />
                          &lt;/restriction>
                        &lt;/complexContent>
                      &lt;/complexType>
                    &lt;/element>
                  &lt;/choice>
                &lt;/sequence>
              &lt;/restriction>
            &lt;/complexContent>
          &lt;/complexType>
        &lt;/element>
      &lt;/sequence>
    &lt;/extension>
  &lt;/complexContent>
&lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectOptionsCommandType", propOrder = { "options" })
public class SelectOptionsCommandType extends AbstractSelectCommandType {

	@XmlElement(required = true)
	protected SelectOptionsCommandType.Options options;

	/**
	 * Gets the value of the options property.
	 * 
	 * @return possible object is {@link SelectOptionsCommandType.Options }
	 * 
	 */
	public SelectOptionsCommandType.Options getOptions() {
		return options;
	}

	/**
	 * Sets the value of the options property.
	 * 
	 * @param value allowed object is {@link SelectOptionsCommandType.Options }
	 * 
	 */
	public void setOptions(SelectOptionsCommandType.Options value) {
		this.options = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 &lt;complexType>
	   &lt;complexContent>
	     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	       &lt;sequence>
	         &lt;choice>
	           &lt;element name="all">
	             &lt;complexType>
	               &lt;complexContent>
	                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	                   &lt;sequence>
	                   &lt;/sequence>
	                 &lt;/restriction>
	               &lt;/complexContent>
	             &lt;/complexType>
	           &lt;/element>
	           &lt;element name="option" maxOccurs="unbounded">
	             &lt;complexType>
	               &lt;complexContent>
	                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	                   &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	                   &lt;attribute name="by" use="required" type="{http://www.ibm.com/selmate}OptionSelectionType" />
	                 &lt;/restriction>
	               &lt;/complexContent>
	             &lt;/complexType>
	           &lt;/element>
	         &lt;/choice>
	       &lt;/sequence>
	     &lt;/restriction>
	   &lt;/complexContent>
	 &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "all", "option" })
	public static class Options {

		protected SelectOptionsCommandType.Options.All all;
		protected List<SelectOptionsCommandType.Options.Option> option;

		/**
		 * Gets the value of the all property.
		 * 
		 * @return possible object is {@link SelectOptionsCommandType.Options.All }
		 * 
		 */
		public SelectOptionsCommandType.Options.All getAll() {
			return all;
		}

		/**
		 * Sets the value of the all property.
		 * 
		 * @param value allowed object is {@link SelectOptionsCommandType.Options.All }
		 * 
		 */
		public void setAll(SelectOptionsCommandType.Options.All value) {
			this.all = value;
		}

		/**
		 * Gets the value of the option property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the option property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getOption().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link SelectOptionsCommandType.Options.Option }
		 * 
		 * 
		 */
		public List<SelectOptionsCommandType.Options.Option> getOption() {
			if (option == null) {
				option = new ArrayList<SelectOptionsCommandType.Options.Option>();
			}
			return this.option;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 &lt;complexType>
		   &lt;complexContent>
		     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		       &lt;sequence>
		       &lt;/sequence>
		     &lt;/restriction>
		   &lt;/complexContent>
		 &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class All {

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 &lt;complexType>
		   &lt;complexContent>
		     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		       &lt;attribute name="by" use="required" type="{http://www.ibm.com/selmate}OptionSelectionType" />
		     &lt;/restriction>
		   &lt;/complexContent>
		 &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Option {

			@XmlAttribute(name = "value", required = true)
			protected String value;
			@XmlAttribute(name = "by", required = true)
			protected OptionSelectionType by;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the by property.
			 * 
			 * @return possible object is {@link OptionSelectionType }
			 * 
			 */
			public OptionSelectionType getBy() {
				return by;
			}

			/**
			 * Sets the value of the by property.
			 * 
			 * @param value allowed object is {@link OptionSelectionType }
			 * 
			 */
			public void setBy(OptionSelectionType value) {
				this.by = value;
			}

		}

	}

}
