//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TimeUnitType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
&lt;simpleType name="TimeUnitType">
  &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
    &lt;enumeration value="s"/>
    &lt;enumeration value="m"/>
    &lt;enumeration value="h"/>
  &lt;/restriction>
&lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TimeUnitType")
@XmlEnum
public enum TimeUnitType {

	@XmlEnumValue("s")
	S("s"), @XmlEnumValue("m")
	M("m"), @XmlEnumValue("h")
	H("h");
	private final String value;

	TimeUnitType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static TimeUnitType fromValue(String v) {
		for (TimeUnitType c : TimeUnitType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
