//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 07:53:38 PM IST 
//

package com.ibm.selmate.jaxb.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for WaitCommandType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
&lt;complexType name="WaitCommandType">
  &lt;complexContent>
    &lt;extension base="{http://www.ibm.com/selmate}AbstractCommandType">
      &lt;sequence>
        &lt;element name="duration">
          &lt;complexType>
            &lt;simpleContent>
              &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>long">
                &lt;attribute name="unit" type="{http://www.ibm.com/selmate}TimeUnitType" />
              &lt;/extension>
            &lt;/simpleContent>
          &lt;/complexType>
        &lt;/element>
      &lt;/sequence>
      &lt;attribute name="type" type="{http://www.ibm.com/selmate}DelayType" />
    &lt;/extension>
  &lt;/complexContent>
&lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WaitCommandType", propOrder = { "duration" })
public class WaitCommandType extends AbstractCommandType {

	@XmlElement(required = true)
	protected WaitCommandType.Duration duration;
	@XmlAttribute(name = "type")
	protected DelayType type;

	/**
	 * Gets the value of the duration property.
	 * 
	 * @return possible object is {@link WaitCommandType.Duration }
	 * 
	 */
	public WaitCommandType.Duration getDuration() {
		return duration;
	}

	/**
	 * Sets the value of the duration property.
	 * 
	 * @param value allowed object is {@link WaitCommandType.Duration }
	 * 
	 */
	public void setDuration(WaitCommandType.Duration value) {
		this.duration = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link DelayType }
	 * 
	 */
	public DelayType getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value allowed object is {@link DelayType }
	 * 
	 */
	public void setType(DelayType value) {
		this.type = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 &lt;complexType>
	   &lt;simpleContent>
	     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>long">
	       &lt;attribute name="unit" type="{http://www.ibm.com/selmate}TimeUnitType" />
	     &lt;/extension>
	   &lt;/simpleContent>
	 &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "value" })
	public static class Duration {

		@XmlValue
		protected long value;
		@XmlAttribute(name = "unit")
		protected TimeUnitType unit;

		/**
		 * Gets the value of the value property.
		 * 
		 */
		public long getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 */
		public void setValue(long value) {
			this.value = value;
		}

		/**
		 * Gets the value of the unit property.
		 * 
		 * @return possible object is {@link TimeUnitType }
		 * 
		 */
		public TimeUnitType getUnit() {
			return unit;
		}

		/**
		 * Sets the value of the unit property.
		 * 
		 * @param value allowed object is {@link TimeUnitType }
		 * 
		 */
		public void setUnit(TimeUnitType value) {
			this.unit = value;
		}

	}

}
